import { Flag, X } from "lucide-react";
import { useState } from "react";
import type { TranslationKey } from "../../i18n/resources";
import { createReport, type ReportReason } from "./reportsApi";

const reasons:ReportReason[]=["harassment","hate_speech","sexual_content","violence","spam","copyright","impersonation","other"];
export function ReportDialog({targetType,targetUserId,targetWorkId,onClose,t}:{targetType:"work"|"user";targetUserId:string;targetWorkId?:string;onClose:()=>void;t:(key:TranslationKey)=>string}){
 const [reason,setReason]=useState<ReportReason>("harassment");const [details,setDetails]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [sent,setSent]=useState(false);
 async function submit(event:React.FormEvent){event.preventDefault();if(busy)return;setBusy(true);setError("");try{await createReport({targetType,targetUserId,targetWorkId,reasonCode:reason,details});setSent(true);}catch(error){setError(error instanceof Error&&error.message.includes("already")?t("reports.duplicate"):t("reports.failed"));}finally{setBusy(false)}}
 return <div className="report-dialog-backdrop" role="presentation" onMouseDown={event=>event.target===event.currentTarget&&!busy&&onClose()}><form className="report-dialog" role="dialog" aria-modal="true" aria-labelledby="report-dialog-title" onSubmit={submit}><button className="report-dialog-close" type="button" aria-label={t("reports.cancel")} disabled={busy} onClick={onClose}><X size={19}/></button><span className="report-dialog-icon"><Flag size={24}/></span><h2 id="report-dialog-title">{t(targetType==="work"?"reports.reportWork":"reports.reportUser")}</h2>{sent?<><p className="report-success" role="status">{t("reports.success")}</p><button className="primary-button" type="button" onClick={onClose}>{t("reports.done")}</button></>:<><p>{t("reports.description")}</p><fieldset><legend>{t("reports.reason")}</legend>{reasons.map(item=><label key={item}><input type="radio" name="report-reason" checked={reason===item} onChange={()=>setReason(item)}/><span>{t(`reports.reason.${item}` as TranslationKey)}</span></label>)}</fieldset><label>{t("reports.details")}<textarea maxLength={2000} value={details} placeholder={t("reports.detailsPlaceholder")} onChange={event=>setDetails(event.target.value)}/><small>{t("reports.detailsHint")}</small></label>{error&&<p className="error-message" role="alert">{error}</p>}<div className="report-dialog-actions"><button type="button" disabled={busy} onClick={onClose}>{t("reports.cancel")}</button><button className="danger-button" type="submit" disabled={busy}>{t(busy?"reports.submitting":"reports.submit")}</button></div></>}</form></div>;
}
